{
    "version": "https://jsonfeed.org/version/1",
    "title": "Security Advisory for Python packages hosted at PyPI.org",
    "home_page_url": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip",
    "feed_url": "https://azu.github.io/github-advisory-database-rss/pip.json",
    "description": "Security Advisory for Python packages hosted at PyPI.org on GitHub",
    "items": [
        {
            "content_html": "<h3 id=\"impact\">Impact</h3>\n<p>An attacker can cause a denial of service via <code>CHECK</code>-fail in  <code>tf.strings.substr</code> with invalid arguments:</p>\n<pre><code class=\"language-python\">import tensorflow as tf\ntf.strings.substr(input='abc', len=1, pos=[1,-1])\n</code></pre>\n<pre><code class=\"language-python\">import tensorflow as tf\ntf.strings.substr(input='abc', len=1, pos=[1,2])\n</code></pre>\n<h3 id=\"patches\">Patches</h3>\n<p>We have received a patch for the issue in GitHub commit <a href=\"https://github.com/tensorflow/tensorflow/commit/890f7164b70354c57d40eda52dcdd7658677c09f\">890f7164b70354c57d40eda52dcdd7658677c09f</a>.</p>\n<p>The fix will be included in TensorFlow 2.5.0. We will also cherrypick this commit on TensorFlow 2.4.2, TensorFlow 2.3.3, TensorFlow 2.2.3 and TensorFlow 2.1.4, as these are also affected and still in supported range.</p>\n<h3 id=\"for-more-information\">For more information</h3>\n<p>Please consult <a href=\"https://github.com/tensorflow/tensorflow/blob/master/SECURITY.md\">our security guide</a> for more information regarding the security model and how to contact us with issues and questions.</p>\n<h3 id=\"attribution\">Attribution</h3>\n<p>This vulnerability has been reported in <a href=\"https://github.com/tensorflow/issues/46900\">#46900</a> and fixed in <a href=\"https://github.com/tensorflow/issues/46974\">#46974</a>.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://github.com/tensorflow/tensorflow/security/advisories/GHSA-mmq6-q8r3-48fm\">https://github.com/tensorflow/tensorflow/security/advisories/GHSA-mmq6-q8r3-48fm</a></li>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2021-29617\">https://nvd.nist.gov/vuln/detail/CVE-2021-29617</a></li>\n<li><a href=\"https://github.com/tensorflow/tensorflow/commit/890f7164b70354c57d40eda52dcdd7658677c09f\">https://github.com/tensorflow/tensorflow/commit/890f7164b70354c57d40eda52dcdd7658677c09f</a></li>\n<li><a href=\"https://github.com/tensorflow/issues/46900\">https://github.com/tensorflow/issues/46900</a></li>\n<li><a href=\"https://github.com/tensorflow/issues/46974\">https://github.com/tensorflow/issues/46974</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/tensorflow-cpu/PYSEC-2021-545.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/tensorflow-cpu/PYSEC-2021-545.yaml</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/tensorflow-gpu/PYSEC-2021-743.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/tensorflow-gpu/PYSEC-2021-743.yaml</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/tensorflow/PYSEC-2021-254.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/tensorflow/PYSEC-2021-254.yaml</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-mmq6-q8r3-48fm\">https://github.com/advisories/GHSA-mmq6-q8r3-48fm</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-mmq6-q8r3-48fm",
            "title": "[tensorflow-gpu] Crash in `tf.strings.substr` due to `CHECK`-fail",
            "date_modified": "2024-11-13T16:28:39.000Z",
            "date_published": "2021-05-21T14:28:50.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-mmq6-q8r3-48fm"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<h3 id=\"impact\">Impact</h3>\n<p>An attacker can cause a denial of service via <code>CHECK</code>-fail in  <code>tf.strings.substr</code> with invalid arguments:</p>\n<pre><code class=\"language-python\">import tensorflow as tf\ntf.strings.substr(input='abc', len=1, pos=[1,-1])\n</code></pre>\n<pre><code class=\"language-python\">import tensorflow as tf\ntf.strings.substr(input='abc', len=1, pos=[1,2])\n</code></pre>\n<h3 id=\"patches\">Patches</h3>\n<p>We have received a patch for the issue in GitHub commit <a href=\"https://github.com/tensorflow/tensorflow/commit/890f7164b70354c57d40eda52dcdd7658677c09f\">890f7164b70354c57d40eda52dcdd7658677c09f</a>.</p>\n<p>The fix will be included in TensorFlow 2.5.0. We will also cherrypick this commit on TensorFlow 2.4.2, TensorFlow 2.3.3, TensorFlow 2.2.3 and TensorFlow 2.1.4, as these are also affected and still in supported range.</p>\n<h3 id=\"for-more-information\">For more information</h3>\n<p>Please consult <a href=\"https://github.com/tensorflow/tensorflow/blob/master/SECURITY.md\">our security guide</a> for more information regarding the security model and how to contact us with issues and questions.</p>\n<h3 id=\"attribution\">Attribution</h3>\n<p>This vulnerability has been reported in <a href=\"https://github.com/tensorflow/issues/46900\">#46900</a> and fixed in <a href=\"https://github.com/tensorflow/issues/46974\">#46974</a>.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://github.com/tensorflow/tensorflow/security/advisories/GHSA-mmq6-q8r3-48fm\">https://github.com/tensorflow/tensorflow/security/advisories/GHSA-mmq6-q8r3-48fm</a></li>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2021-29617\">https://nvd.nist.gov/vuln/detail/CVE-2021-29617</a></li>\n<li><a href=\"https://github.com/tensorflow/tensorflow/commit/890f7164b70354c57d40eda52dcdd7658677c09f\">https://github.com/tensorflow/tensorflow/commit/890f7164b70354c57d40eda52dcdd7658677c09f</a></li>\n<li><a href=\"https://github.com/tensorflow/issues/46900\">https://github.com/tensorflow/issues/46900</a></li>\n<li><a href=\"https://github.com/tensorflow/issues/46974\">https://github.com/tensorflow/issues/46974</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/tensorflow-cpu/PYSEC-2021-545.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/tensorflow-cpu/PYSEC-2021-545.yaml</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/tensorflow-gpu/PYSEC-2021-743.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/tensorflow-gpu/PYSEC-2021-743.yaml</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/tensorflow/PYSEC-2021-254.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/tensorflow/PYSEC-2021-254.yaml</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-mmq6-q8r3-48fm\">https://github.com/advisories/GHSA-mmq6-q8r3-48fm</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-mmq6-q8r3-48fm",
            "title": "[tensorflow-gpu] Crash in `tf.strings.substr` due to `CHECK`-fail",
            "date_modified": "2024-11-13T16:28:39.000Z",
            "date_published": "2021-05-21T14:28:50.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-mmq6-q8r3-48fm"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<h3 id=\"impact\">Impact</h3>\n<p>An attacker can cause a denial of service via <code>CHECK</code>-fail in  <code>tf.strings.substr</code> with invalid arguments:</p>\n<pre><code class=\"language-python\">import tensorflow as tf\ntf.strings.substr(input='abc', len=1, pos=[1,-1])\n</code></pre>\n<pre><code class=\"language-python\">import tensorflow as tf\ntf.strings.substr(input='abc', len=1, pos=[1,2])\n</code></pre>\n<h3 id=\"patches\">Patches</h3>\n<p>We have received a patch for the issue in GitHub commit <a href=\"https://github.com/tensorflow/tensorflow/commit/890f7164b70354c57d40eda52dcdd7658677c09f\">890f7164b70354c57d40eda52dcdd7658677c09f</a>.</p>\n<p>The fix will be included in TensorFlow 2.5.0. We will also cherrypick this commit on TensorFlow 2.4.2, TensorFlow 2.3.3, TensorFlow 2.2.3 and TensorFlow 2.1.4, as these are also affected and still in supported range.</p>\n<h3 id=\"for-more-information\">For more information</h3>\n<p>Please consult <a href=\"https://github.com/tensorflow/tensorflow/blob/master/SECURITY.md\">our security guide</a> for more information regarding the security model and how to contact us with issues and questions.</p>\n<h3 id=\"attribution\">Attribution</h3>\n<p>This vulnerability has been reported in <a href=\"https://github.com/tensorflow/issues/46900\">#46900</a> and fixed in <a href=\"https://github.com/tensorflow/issues/46974\">#46974</a>.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://github.com/tensorflow/tensorflow/security/advisories/GHSA-mmq6-q8r3-48fm\">https://github.com/tensorflow/tensorflow/security/advisories/GHSA-mmq6-q8r3-48fm</a></li>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2021-29617\">https://nvd.nist.gov/vuln/detail/CVE-2021-29617</a></li>\n<li><a href=\"https://github.com/tensorflow/tensorflow/commit/890f7164b70354c57d40eda52dcdd7658677c09f\">https://github.com/tensorflow/tensorflow/commit/890f7164b70354c57d40eda52dcdd7658677c09f</a></li>\n<li><a href=\"https://github.com/tensorflow/issues/46900\">https://github.com/tensorflow/issues/46900</a></li>\n<li><a href=\"https://github.com/tensorflow/issues/46974\">https://github.com/tensorflow/issues/46974</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/tensorflow-cpu/PYSEC-2021-545.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/tensorflow-cpu/PYSEC-2021-545.yaml</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/tensorflow-gpu/PYSEC-2021-743.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/tensorflow-gpu/PYSEC-2021-743.yaml</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/tensorflow/PYSEC-2021-254.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/tensorflow/PYSEC-2021-254.yaml</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-mmq6-q8r3-48fm\">https://github.com/advisories/GHSA-mmq6-q8r3-48fm</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-mmq6-q8r3-48fm",
            "title": "[tensorflow-gpu] Crash in `tf.strings.substr` due to `CHECK`-fail",
            "date_modified": "2024-11-13T16:28:39.000Z",
            "date_published": "2021-05-21T14:28:50.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-mmq6-q8r3-48fm"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<h3 id=\"impact\">Impact</h3>\n<p>An attacker can cause a denial of service via <code>CHECK</code>-fail in  <code>tf.strings.substr</code> with invalid arguments:</p>\n<pre><code class=\"language-python\">import tensorflow as tf\ntf.strings.substr(input='abc', len=1, pos=[1,-1])\n</code></pre>\n<pre><code class=\"language-python\">import tensorflow as tf\ntf.strings.substr(input='abc', len=1, pos=[1,2])\n</code></pre>\n<h3 id=\"patches\">Patches</h3>\n<p>We have received a patch for the issue in GitHub commit <a href=\"https://github.com/tensorflow/tensorflow/commit/890f7164b70354c57d40eda52dcdd7658677c09f\">890f7164b70354c57d40eda52dcdd7658677c09f</a>.</p>\n<p>The fix will be included in TensorFlow 2.5.0. We will also cherrypick this commit on TensorFlow 2.4.2, TensorFlow 2.3.3, TensorFlow 2.2.3 and TensorFlow 2.1.4, as these are also affected and still in supported range.</p>\n<h3 id=\"for-more-information\">For more information</h3>\n<p>Please consult <a href=\"https://github.com/tensorflow/tensorflow/blob/master/SECURITY.md\">our security guide</a> for more information regarding the security model and how to contact us with issues and questions.</p>\n<h3 id=\"attribution\">Attribution</h3>\n<p>This vulnerability has been reported in <a href=\"https://github.com/tensorflow/issues/46900\">#46900</a> and fixed in <a href=\"https://github.com/tensorflow/issues/46974\">#46974</a>.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://github.com/tensorflow/tensorflow/security/advisories/GHSA-mmq6-q8r3-48fm\">https://github.com/tensorflow/tensorflow/security/advisories/GHSA-mmq6-q8r3-48fm</a></li>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2021-29617\">https://nvd.nist.gov/vuln/detail/CVE-2021-29617</a></li>\n<li><a href=\"https://github.com/tensorflow/tensorflow/commit/890f7164b70354c57d40eda52dcdd7658677c09f\">https://github.com/tensorflow/tensorflow/commit/890f7164b70354c57d40eda52dcdd7658677c09f</a></li>\n<li><a href=\"https://github.com/tensorflow/issues/46900\">https://github.com/tensorflow/issues/46900</a></li>\n<li><a href=\"https://github.com/tensorflow/issues/46974\">https://github.com/tensorflow/issues/46974</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/tensorflow-cpu/PYSEC-2021-545.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/tensorflow-cpu/PYSEC-2021-545.yaml</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/tensorflow-gpu/PYSEC-2021-743.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/tensorflow-gpu/PYSEC-2021-743.yaml</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/tensorflow/PYSEC-2021-254.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/tensorflow/PYSEC-2021-254.yaml</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-mmq6-q8r3-48fm\">https://github.com/advisories/GHSA-mmq6-q8r3-48fm</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-mmq6-q8r3-48fm",
            "title": "[tensorflow-gpu] Crash in `tf.strings.substr` due to `CHECK`-fail",
            "date_modified": "2024-11-13T16:28:39.000Z",
            "date_published": "2021-05-21T14:28:50.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-mmq6-q8r3-48fm"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<h3 id=\"impact\">Impact</h3>\n<p>An attacker can cause a denial of service via <code>CHECK</code>-fail in  <code>tf.strings.substr</code> with invalid arguments:</p>\n<pre><code class=\"language-python\">import tensorflow as tf\ntf.strings.substr(input='abc', len=1, pos=[1,-1])\n</code></pre>\n<pre><code class=\"language-python\">import tensorflow as tf\ntf.strings.substr(input='abc', len=1, pos=[1,2])\n</code></pre>\n<h3 id=\"patches\">Patches</h3>\n<p>We have received a patch for the issue in GitHub commit <a href=\"https://github.com/tensorflow/tensorflow/commit/890f7164b70354c57d40eda52dcdd7658677c09f\">890f7164b70354c57d40eda52dcdd7658677c09f</a>.</p>\n<p>The fix will be included in TensorFlow 2.5.0. We will also cherrypick this commit on TensorFlow 2.4.2, TensorFlow 2.3.3, TensorFlow 2.2.3 and TensorFlow 2.1.4, as these are also affected and still in supported range.</p>\n<h3 id=\"for-more-information\">For more information</h3>\n<p>Please consult <a href=\"https://github.com/tensorflow/tensorflow/blob/master/SECURITY.md\">our security guide</a> for more information regarding the security model and how to contact us with issues and questions.</p>\n<h3 id=\"attribution\">Attribution</h3>\n<p>This vulnerability has been reported in <a href=\"https://github.com/tensorflow/issues/46900\">#46900</a> and fixed in <a href=\"https://github.com/tensorflow/issues/46974\">#46974</a>.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://github.com/tensorflow/tensorflow/security/advisories/GHSA-mmq6-q8r3-48fm\">https://github.com/tensorflow/tensorflow/security/advisories/GHSA-mmq6-q8r3-48fm</a></li>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2021-29617\">https://nvd.nist.gov/vuln/detail/CVE-2021-29617</a></li>\n<li><a href=\"https://github.com/tensorflow/tensorflow/commit/890f7164b70354c57d40eda52dcdd7658677c09f\">https://github.com/tensorflow/tensorflow/commit/890f7164b70354c57d40eda52dcdd7658677c09f</a></li>\n<li><a href=\"https://github.com/tensorflow/issues/46900\">https://github.com/tensorflow/issues/46900</a></li>\n<li><a href=\"https://github.com/tensorflow/issues/46974\">https://github.com/tensorflow/issues/46974</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/tensorflow-cpu/PYSEC-2021-545.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/tensorflow-cpu/PYSEC-2021-545.yaml</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/tensorflow-gpu/PYSEC-2021-743.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/tensorflow-gpu/PYSEC-2021-743.yaml</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/tensorflow/PYSEC-2021-254.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/tensorflow/PYSEC-2021-254.yaml</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-mmq6-q8r3-48fm\">https://github.com/advisories/GHSA-mmq6-q8r3-48fm</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-mmq6-q8r3-48fm",
            "title": "[tensorflow-cpu] Crash in `tf.strings.substr` due to `CHECK`-fail",
            "date_modified": "2024-11-13T16:28:39.000Z",
            "date_published": "2021-05-21T14:28:50.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-mmq6-q8r3-48fm"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<h3 id=\"impact\">Impact</h3>\n<p>An attacker can cause a denial of service via <code>CHECK</code>-fail in  <code>tf.strings.substr</code> with invalid arguments:</p>\n<pre><code class=\"language-python\">import tensorflow as tf\ntf.strings.substr(input='abc', len=1, pos=[1,-1])\n</code></pre>\n<pre><code class=\"language-python\">import tensorflow as tf\ntf.strings.substr(input='abc', len=1, pos=[1,2])\n</code></pre>\n<h3 id=\"patches\">Patches</h3>\n<p>We have received a patch for the issue in GitHub commit <a href=\"https://github.com/tensorflow/tensorflow/commit/890f7164b70354c57d40eda52dcdd7658677c09f\">890f7164b70354c57d40eda52dcdd7658677c09f</a>.</p>\n<p>The fix will be included in TensorFlow 2.5.0. We will also cherrypick this commit on TensorFlow 2.4.2, TensorFlow 2.3.3, TensorFlow 2.2.3 and TensorFlow 2.1.4, as these are also affected and still in supported range.</p>\n<h3 id=\"for-more-information\">For more information</h3>\n<p>Please consult <a href=\"https://github.com/tensorflow/tensorflow/blob/master/SECURITY.md\">our security guide</a> for more information regarding the security model and how to contact us with issues and questions.</p>\n<h3 id=\"attribution\">Attribution</h3>\n<p>This vulnerability has been reported in <a href=\"https://github.com/tensorflow/issues/46900\">#46900</a> and fixed in <a href=\"https://github.com/tensorflow/issues/46974\">#46974</a>.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://github.com/tensorflow/tensorflow/security/advisories/GHSA-mmq6-q8r3-48fm\">https://github.com/tensorflow/tensorflow/security/advisories/GHSA-mmq6-q8r3-48fm</a></li>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2021-29617\">https://nvd.nist.gov/vuln/detail/CVE-2021-29617</a></li>\n<li><a href=\"https://github.com/tensorflow/tensorflow/commit/890f7164b70354c57d40eda52dcdd7658677c09f\">https://github.com/tensorflow/tensorflow/commit/890f7164b70354c57d40eda52dcdd7658677c09f</a></li>\n<li><a href=\"https://github.com/tensorflow/issues/46900\">https://github.com/tensorflow/issues/46900</a></li>\n<li><a href=\"https://github.com/tensorflow/issues/46974\">https://github.com/tensorflow/issues/46974</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/tensorflow-cpu/PYSEC-2021-545.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/tensorflow-cpu/PYSEC-2021-545.yaml</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/tensorflow-gpu/PYSEC-2021-743.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/tensorflow-gpu/PYSEC-2021-743.yaml</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/tensorflow/PYSEC-2021-254.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/tensorflow/PYSEC-2021-254.yaml</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-mmq6-q8r3-48fm\">https://github.com/advisories/GHSA-mmq6-q8r3-48fm</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-mmq6-q8r3-48fm",
            "title": "[tensorflow-cpu] Crash in `tf.strings.substr` due to `CHECK`-fail",
            "date_modified": "2024-11-13T16:28:39.000Z",
            "date_published": "2021-05-21T14:28:50.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-mmq6-q8r3-48fm"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<h3 id=\"impact\">Impact</h3>\n<p>An attacker can cause a denial of service via <code>CHECK</code>-fail in  <code>tf.strings.substr</code> with invalid arguments:</p>\n<pre><code class=\"language-python\">import tensorflow as tf\ntf.strings.substr(input='abc', len=1, pos=[1,-1])\n</code></pre>\n<pre><code class=\"language-python\">import tensorflow as tf\ntf.strings.substr(input='abc', len=1, pos=[1,2])\n</code></pre>\n<h3 id=\"patches\">Patches</h3>\n<p>We have received a patch for the issue in GitHub commit <a href=\"https://github.com/tensorflow/tensorflow/commit/890f7164b70354c57d40eda52dcdd7658677c09f\">890f7164b70354c57d40eda52dcdd7658677c09f</a>.</p>\n<p>The fix will be included in TensorFlow 2.5.0. We will also cherrypick this commit on TensorFlow 2.4.2, TensorFlow 2.3.3, TensorFlow 2.2.3 and TensorFlow 2.1.4, as these are also affected and still in supported range.</p>\n<h3 id=\"for-more-information\">For more information</h3>\n<p>Please consult <a href=\"https://github.com/tensorflow/tensorflow/blob/master/SECURITY.md\">our security guide</a> for more information regarding the security model and how to contact us with issues and questions.</p>\n<h3 id=\"attribution\">Attribution</h3>\n<p>This vulnerability has been reported in <a href=\"https://github.com/tensorflow/issues/46900\">#46900</a> and fixed in <a href=\"https://github.com/tensorflow/issues/46974\">#46974</a>.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://github.com/tensorflow/tensorflow/security/advisories/GHSA-mmq6-q8r3-48fm\">https://github.com/tensorflow/tensorflow/security/advisories/GHSA-mmq6-q8r3-48fm</a></li>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2021-29617\">https://nvd.nist.gov/vuln/detail/CVE-2021-29617</a></li>\n<li><a href=\"https://github.com/tensorflow/tensorflow/commit/890f7164b70354c57d40eda52dcdd7658677c09f\">https://github.com/tensorflow/tensorflow/commit/890f7164b70354c57d40eda52dcdd7658677c09f</a></li>\n<li><a href=\"https://github.com/tensorflow/issues/46900\">https://github.com/tensorflow/issues/46900</a></li>\n<li><a href=\"https://github.com/tensorflow/issues/46974\">https://github.com/tensorflow/issues/46974</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/tensorflow-cpu/PYSEC-2021-545.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/tensorflow-cpu/PYSEC-2021-545.yaml</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/tensorflow-gpu/PYSEC-2021-743.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/tensorflow-gpu/PYSEC-2021-743.yaml</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/tensorflow/PYSEC-2021-254.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/tensorflow/PYSEC-2021-254.yaml</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-mmq6-q8r3-48fm\">https://github.com/advisories/GHSA-mmq6-q8r3-48fm</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-mmq6-q8r3-48fm",
            "title": "[tensorflow-cpu] Crash in `tf.strings.substr` due to `CHECK`-fail",
            "date_modified": "2024-11-13T16:28:39.000Z",
            "date_published": "2021-05-21T14:28:50.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-mmq6-q8r3-48fm"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<h3 id=\"impact\">Impact</h3>\n<p>An attacker can cause a denial of service via <code>CHECK</code>-fail in  <code>tf.strings.substr</code> with invalid arguments:</p>\n<pre><code class=\"language-python\">import tensorflow as tf\ntf.strings.substr(input='abc', len=1, pos=[1,-1])\n</code></pre>\n<pre><code class=\"language-python\">import tensorflow as tf\ntf.strings.substr(input='abc', len=1, pos=[1,2])\n</code></pre>\n<h3 id=\"patches\">Patches</h3>\n<p>We have received a patch for the issue in GitHub commit <a href=\"https://github.com/tensorflow/tensorflow/commit/890f7164b70354c57d40eda52dcdd7658677c09f\">890f7164b70354c57d40eda52dcdd7658677c09f</a>.</p>\n<p>The fix will be included in TensorFlow 2.5.0. We will also cherrypick this commit on TensorFlow 2.4.2, TensorFlow 2.3.3, TensorFlow 2.2.3 and TensorFlow 2.1.4, as these are also affected and still in supported range.</p>\n<h3 id=\"for-more-information\">For more information</h3>\n<p>Please consult <a href=\"https://github.com/tensorflow/tensorflow/blob/master/SECURITY.md\">our security guide</a> for more information regarding the security model and how to contact us with issues and questions.</p>\n<h3 id=\"attribution\">Attribution</h3>\n<p>This vulnerability has been reported in <a href=\"https://github.com/tensorflow/issues/46900\">#46900</a> and fixed in <a href=\"https://github.com/tensorflow/issues/46974\">#46974</a>.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://github.com/tensorflow/tensorflow/security/advisories/GHSA-mmq6-q8r3-48fm\">https://github.com/tensorflow/tensorflow/security/advisories/GHSA-mmq6-q8r3-48fm</a></li>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2021-29617\">https://nvd.nist.gov/vuln/detail/CVE-2021-29617</a></li>\n<li><a href=\"https://github.com/tensorflow/tensorflow/commit/890f7164b70354c57d40eda52dcdd7658677c09f\">https://github.com/tensorflow/tensorflow/commit/890f7164b70354c57d40eda52dcdd7658677c09f</a></li>\n<li><a href=\"https://github.com/tensorflow/issues/46900\">https://github.com/tensorflow/issues/46900</a></li>\n<li><a href=\"https://github.com/tensorflow/issues/46974\">https://github.com/tensorflow/issues/46974</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/tensorflow-cpu/PYSEC-2021-545.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/tensorflow-cpu/PYSEC-2021-545.yaml</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/tensorflow-gpu/PYSEC-2021-743.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/tensorflow-gpu/PYSEC-2021-743.yaml</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/tensorflow/PYSEC-2021-254.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/tensorflow/PYSEC-2021-254.yaml</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-mmq6-q8r3-48fm\">https://github.com/advisories/GHSA-mmq6-q8r3-48fm</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-mmq6-q8r3-48fm",
            "title": "[tensorflow-cpu] Crash in `tf.strings.substr` due to `CHECK`-fail",
            "date_modified": "2024-11-13T16:28:39.000Z",
            "date_published": "2021-05-21T14:28:50.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-mmq6-q8r3-48fm"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<h3 id=\"impact\">Impact</h3>\n<p>An attacker can cause a denial of service via <code>CHECK</code>-fail in  <code>tf.strings.substr</code> with invalid arguments:</p>\n<pre><code class=\"language-python\">import tensorflow as tf\ntf.strings.substr(input='abc', len=1, pos=[1,-1])\n</code></pre>\n<pre><code class=\"language-python\">import tensorflow as tf\ntf.strings.substr(input='abc', len=1, pos=[1,2])\n</code></pre>\n<h3 id=\"patches\">Patches</h3>\n<p>We have received a patch for the issue in GitHub commit <a href=\"https://github.com/tensorflow/tensorflow/commit/890f7164b70354c57d40eda52dcdd7658677c09f\">890f7164b70354c57d40eda52dcdd7658677c09f</a>.</p>\n<p>The fix will be included in TensorFlow 2.5.0. We will also cherrypick this commit on TensorFlow 2.4.2, TensorFlow 2.3.3, TensorFlow 2.2.3 and TensorFlow 2.1.4, as these are also affected and still in supported range.</p>\n<h3 id=\"for-more-information\">For more information</h3>\n<p>Please consult <a href=\"https://github.com/tensorflow/tensorflow/blob/master/SECURITY.md\">our security guide</a> for more information regarding the security model and how to contact us with issues and questions.</p>\n<h3 id=\"attribution\">Attribution</h3>\n<p>This vulnerability has been reported in <a href=\"https://github.com/tensorflow/issues/46900\">#46900</a> and fixed in <a href=\"https://github.com/tensorflow/issues/46974\">#46974</a>.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://github.com/tensorflow/tensorflow/security/advisories/GHSA-mmq6-q8r3-48fm\">https://github.com/tensorflow/tensorflow/security/advisories/GHSA-mmq6-q8r3-48fm</a></li>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2021-29617\">https://nvd.nist.gov/vuln/detail/CVE-2021-29617</a></li>\n<li><a href=\"https://github.com/tensorflow/tensorflow/commit/890f7164b70354c57d40eda52dcdd7658677c09f\">https://github.com/tensorflow/tensorflow/commit/890f7164b70354c57d40eda52dcdd7658677c09f</a></li>\n<li><a href=\"https://github.com/tensorflow/issues/46900\">https://github.com/tensorflow/issues/46900</a></li>\n<li><a href=\"https://github.com/tensorflow/issues/46974\">https://github.com/tensorflow/issues/46974</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/tensorflow-cpu/PYSEC-2021-545.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/tensorflow-cpu/PYSEC-2021-545.yaml</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/tensorflow-gpu/PYSEC-2021-743.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/tensorflow-gpu/PYSEC-2021-743.yaml</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/tensorflow/PYSEC-2021-254.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/tensorflow/PYSEC-2021-254.yaml</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-mmq6-q8r3-48fm\">https://github.com/advisories/GHSA-mmq6-q8r3-48fm</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-mmq6-q8r3-48fm",
            "title": "[tensorflow] Crash in `tf.strings.substr` due to `CHECK`-fail",
            "date_modified": "2024-11-13T16:28:39.000Z",
            "date_published": "2021-05-21T14:28:50.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-mmq6-q8r3-48fm"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<h3 id=\"impact\">Impact</h3>\n<p>An attacker can cause a denial of service via <code>CHECK</code>-fail in  <code>tf.strings.substr</code> with invalid arguments:</p>\n<pre><code class=\"language-python\">import tensorflow as tf\ntf.strings.substr(input='abc', len=1, pos=[1,-1])\n</code></pre>\n<pre><code class=\"language-python\">import tensorflow as tf\ntf.strings.substr(input='abc', len=1, pos=[1,2])\n</code></pre>\n<h3 id=\"patches\">Patches</h3>\n<p>We have received a patch for the issue in GitHub commit <a href=\"https://github.com/tensorflow/tensorflow/commit/890f7164b70354c57d40eda52dcdd7658677c09f\">890f7164b70354c57d40eda52dcdd7658677c09f</a>.</p>\n<p>The fix will be included in TensorFlow 2.5.0. We will also cherrypick this commit on TensorFlow 2.4.2, TensorFlow 2.3.3, TensorFlow 2.2.3 and TensorFlow 2.1.4, as these are also affected and still in supported range.</p>\n<h3 id=\"for-more-information\">For more information</h3>\n<p>Please consult <a href=\"https://github.com/tensorflow/tensorflow/blob/master/SECURITY.md\">our security guide</a> for more information regarding the security model and how to contact us with issues and questions.</p>\n<h3 id=\"attribution\">Attribution</h3>\n<p>This vulnerability has been reported in <a href=\"https://github.com/tensorflow/issues/46900\">#46900</a> and fixed in <a href=\"https://github.com/tensorflow/issues/46974\">#46974</a>.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://github.com/tensorflow/tensorflow/security/advisories/GHSA-mmq6-q8r3-48fm\">https://github.com/tensorflow/tensorflow/security/advisories/GHSA-mmq6-q8r3-48fm</a></li>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2021-29617\">https://nvd.nist.gov/vuln/detail/CVE-2021-29617</a></li>\n<li><a href=\"https://github.com/tensorflow/tensorflow/commit/890f7164b70354c57d40eda52dcdd7658677c09f\">https://github.com/tensorflow/tensorflow/commit/890f7164b70354c57d40eda52dcdd7658677c09f</a></li>\n<li><a href=\"https://github.com/tensorflow/issues/46900\">https://github.com/tensorflow/issues/46900</a></li>\n<li><a href=\"https://github.com/tensorflow/issues/46974\">https://github.com/tensorflow/issues/46974</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/tensorflow-cpu/PYSEC-2021-545.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/tensorflow-cpu/PYSEC-2021-545.yaml</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/tensorflow-gpu/PYSEC-2021-743.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/tensorflow-gpu/PYSEC-2021-743.yaml</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/tensorflow/PYSEC-2021-254.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/tensorflow/PYSEC-2021-254.yaml</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-mmq6-q8r3-48fm\">https://github.com/advisories/GHSA-mmq6-q8r3-48fm</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-mmq6-q8r3-48fm",
            "title": "[tensorflow] Crash in `tf.strings.substr` due to `CHECK`-fail",
            "date_modified": "2024-11-13T16:28:39.000Z",
            "date_published": "2021-05-21T14:28:50.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-mmq6-q8r3-48fm"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<h3 id=\"impact\">Impact</h3>\n<p>An attacker can cause a denial of service via <code>CHECK</code>-fail in  <code>tf.strings.substr</code> with invalid arguments:</p>\n<pre><code class=\"language-python\">import tensorflow as tf\ntf.strings.substr(input='abc', len=1, pos=[1,-1])\n</code></pre>\n<pre><code class=\"language-python\">import tensorflow as tf\ntf.strings.substr(input='abc', len=1, pos=[1,2])\n</code></pre>\n<h3 id=\"patches\">Patches</h3>\n<p>We have received a patch for the issue in GitHub commit <a href=\"https://github.com/tensorflow/tensorflow/commit/890f7164b70354c57d40eda52dcdd7658677c09f\">890f7164b70354c57d40eda52dcdd7658677c09f</a>.</p>\n<p>The fix will be included in TensorFlow 2.5.0. We will also cherrypick this commit on TensorFlow 2.4.2, TensorFlow 2.3.3, TensorFlow 2.2.3 and TensorFlow 2.1.4, as these are also affected and still in supported range.</p>\n<h3 id=\"for-more-information\">For more information</h3>\n<p>Please consult <a href=\"https://github.com/tensorflow/tensorflow/blob/master/SECURITY.md\">our security guide</a> for more information regarding the security model and how to contact us with issues and questions.</p>\n<h3 id=\"attribution\">Attribution</h3>\n<p>This vulnerability has been reported in <a href=\"https://github.com/tensorflow/issues/46900\">#46900</a> and fixed in <a href=\"https://github.com/tensorflow/issues/46974\">#46974</a>.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://github.com/tensorflow/tensorflow/security/advisories/GHSA-mmq6-q8r3-48fm\">https://github.com/tensorflow/tensorflow/security/advisories/GHSA-mmq6-q8r3-48fm</a></li>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2021-29617\">https://nvd.nist.gov/vuln/detail/CVE-2021-29617</a></li>\n<li><a href=\"https://github.com/tensorflow/tensorflow/commit/890f7164b70354c57d40eda52dcdd7658677c09f\">https://github.com/tensorflow/tensorflow/commit/890f7164b70354c57d40eda52dcdd7658677c09f</a></li>\n<li><a href=\"https://github.com/tensorflow/issues/46900\">https://github.com/tensorflow/issues/46900</a></li>\n<li><a href=\"https://github.com/tensorflow/issues/46974\">https://github.com/tensorflow/issues/46974</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/tensorflow-cpu/PYSEC-2021-545.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/tensorflow-cpu/PYSEC-2021-545.yaml</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/tensorflow-gpu/PYSEC-2021-743.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/tensorflow-gpu/PYSEC-2021-743.yaml</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/tensorflow/PYSEC-2021-254.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/tensorflow/PYSEC-2021-254.yaml</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-mmq6-q8r3-48fm\">https://github.com/advisories/GHSA-mmq6-q8r3-48fm</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-mmq6-q8r3-48fm",
            "title": "[tensorflow] Crash in `tf.strings.substr` due to `CHECK`-fail",
            "date_modified": "2024-11-13T16:28:39.000Z",
            "date_published": "2021-05-21T14:28:50.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-mmq6-q8r3-48fm"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<h3 id=\"impact\">Impact</h3>\n<p>An attacker can cause a denial of service via <code>CHECK</code>-fail in  <code>tf.strings.substr</code> with invalid arguments:</p>\n<pre><code class=\"language-python\">import tensorflow as tf\ntf.strings.substr(input='abc', len=1, pos=[1,-1])\n</code></pre>\n<pre><code class=\"language-python\">import tensorflow as tf\ntf.strings.substr(input='abc', len=1, pos=[1,2])\n</code></pre>\n<h3 id=\"patches\">Patches</h3>\n<p>We have received a patch for the issue in GitHub commit <a href=\"https://github.com/tensorflow/tensorflow/commit/890f7164b70354c57d40eda52dcdd7658677c09f\">890f7164b70354c57d40eda52dcdd7658677c09f</a>.</p>\n<p>The fix will be included in TensorFlow 2.5.0. We will also cherrypick this commit on TensorFlow 2.4.2, TensorFlow 2.3.3, TensorFlow 2.2.3 and TensorFlow 2.1.4, as these are also affected and still in supported range.</p>\n<h3 id=\"for-more-information\">For more information</h3>\n<p>Please consult <a href=\"https://github.com/tensorflow/tensorflow/blob/master/SECURITY.md\">our security guide</a> for more information regarding the security model and how to contact us with issues and questions.</p>\n<h3 id=\"attribution\">Attribution</h3>\n<p>This vulnerability has been reported in <a href=\"https://github.com/tensorflow/issues/46900\">#46900</a> and fixed in <a href=\"https://github.com/tensorflow/issues/46974\">#46974</a>.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://github.com/tensorflow/tensorflow/security/advisories/GHSA-mmq6-q8r3-48fm\">https://github.com/tensorflow/tensorflow/security/advisories/GHSA-mmq6-q8r3-48fm</a></li>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2021-29617\">https://nvd.nist.gov/vuln/detail/CVE-2021-29617</a></li>\n<li><a href=\"https://github.com/tensorflow/tensorflow/commit/890f7164b70354c57d40eda52dcdd7658677c09f\">https://github.com/tensorflow/tensorflow/commit/890f7164b70354c57d40eda52dcdd7658677c09f</a></li>\n<li><a href=\"https://github.com/tensorflow/issues/46900\">https://github.com/tensorflow/issues/46900</a></li>\n<li><a href=\"https://github.com/tensorflow/issues/46974\">https://github.com/tensorflow/issues/46974</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/tensorflow-cpu/PYSEC-2021-545.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/tensorflow-cpu/PYSEC-2021-545.yaml</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/tensorflow-gpu/PYSEC-2021-743.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/tensorflow-gpu/PYSEC-2021-743.yaml</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/tensorflow/PYSEC-2021-254.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/tensorflow/PYSEC-2021-254.yaml</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-mmq6-q8r3-48fm\">https://github.com/advisories/GHSA-mmq6-q8r3-48fm</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-mmq6-q8r3-48fm",
            "title": "[tensorflow] Crash in `tf.strings.substr` due to `CHECK`-fail",
            "date_modified": "2024-11-13T16:28:39.000Z",
            "date_published": "2021-05-21T14:28:50.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-mmq6-q8r3-48fm"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>A flaw was found in Ansible-Core. This vulnerability allows attackers to bypass unsafe content protections using the hostvars object to reference and execute templated content. This issue can lead to arbitrary code execution if remote data or module outputs are improperly templated within playbooks.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2024-11079\">https://nvd.nist.gov/vuln/detail/CVE-2024-11079</a></li>\n<li><a href=\"https://access.redhat.com/security/cve/CVE-2024-11079\">https://access.redhat.com/security/cve/CVE-2024-11079</a></li>\n<li><a href=\"https://bugzilla.redhat.com/show_bug.cgi?id=2325171\">https://bugzilla.redhat.com/show_bug.cgi?id=2325171</a></li>\n<li><a href=\"https://github.com/ansible/ansible/pull/84299\">https://github.com/ansible/ansible/pull/84299</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-99w6-3xph-cx78\">https://github.com/advisories/GHSA-99w6-3xph-cx78</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-99w6-3xph-cx78",
            "title": "[ansible-core] Ansible-Core vulnerable to content protections bypass",
            "date_modified": "2024-11-12T21:35:38.000Z",
            "date_published": "2024-11-12T00:30:36.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-99w6-3xph-cx78"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>wasm3 at commit 139076a contains a memory leak in the Read_utf8 function.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2024-27529\">https://nvd.nist.gov/vuln/detail/CVE-2024-27529</a></li>\n<li><a href=\"https://github.com/wasm3/wasm3/issues/462\">https://github.com/wasm3/wasm3/issues/462</a></li>\n<li><a href=\"https://gist.github.com/haruki3hhh/ac70bd83b9c0ed1de6289d818488da78\">https://gist.github.com/haruki3hhh/ac70bd83b9c0ed1de6289d818488da78</a></li>\n<li><a href=\"https://github.com/wasm3/wasm3/pull/490\">https://github.com/wasm3/wasm3/pull/490</a></li>\n<li><a href=\"https://github.com/wasm3/wasm3/commit/526c1251b64e6e9fdc0d40c768ae46cd20338594\">https://github.com/wasm3/wasm3/commit/526c1251b64e6e9fdc0d40c768ae46cd20338594</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-fmq6-4w57-2w3v\">https://github.com/advisories/GHSA-fmq6-4w57-2w3v</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-fmq6-4w57-2w3v",
            "title": "[pywasm3] wasm3 uncontrolled memory allocation vulnerability",
            "date_modified": "2024-11-12T20:46:55.000Z",
            "date_published": "2024-11-09T00:30:42.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-fmq6-4w57-2w3v"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>A vulnerability in the GraphCypherQAChain class of langchain-ai/langchain version 0.2.5 allows for SQL injection through prompt injection. This vulnerability can lead to unauthorized data manipulation, data exfiltration, denial of service (DoS) by deleting all data, breaches in multi-tenant security environments, and data integrity issues. Attackers can create, update, or delete nodes and relationships without proper authorization, extract sensitive data, disrupt services, access data across different tenants, and compromise the integrity of the database.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2024-8309\">https://nvd.nist.gov/vuln/detail/CVE-2024-8309</a></li>\n<li><a href=\"https://github.com/langchain-ai/langchain/commit/c2a3021bb0c5f54649d380b42a0684ca5778c255\">https://github.com/langchain-ai/langchain/commit/c2a3021bb0c5f54649d380b42a0684ca5778c255</a></li>\n<li><a href=\"https://huntr.com/bounties/8f4ad910-7fdc-4089-8f0a-b5df5f32e7c5\">https://huntr.com/bounties/8f4ad910-7fdc-4089-8f0a-b5df5f32e7c5</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/langchain/PYSEC-2024-115.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/langchain/PYSEC-2024-115.yaml</a></li>\n<li><a href=\"https://github.com/langchain-ai/langchain/commit/64c317eba05fbac0c6a6fc5aa192bc0d7130972e\">https://github.com/langchain-ai/langchain/commit/64c317eba05fbac0c6a6fc5aa192bc0d7130972e</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-45pg-36p6-83v9\">https://github.com/advisories/GHSA-45pg-36p6-83v9</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-45pg-36p6-83v9",
            "title": "[langchain-community] Langchain SQL Injection vulnerability",
            "date_modified": "2024-11-12T19:58:00.000Z",
            "date_published": "2024-10-29T15:32:05.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-45pg-36p6-83v9"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<h3 id=\"impact\">Impact</h3>\n<p>This is a kind of moderate issue. The impact is not big for normal users but can be for users who want to secure their code/files/etc.</p>\n<p>The issue is that the map of encoding/decoding languages are visible in code. </p>\n<h3 id=\"patches\">Patches</h3>\n<p>The Problem was patched in 0.2.5, so you should try to upgrade to the 0.2.5 version.</p>\n<h3 id=\"for-025-version-users\">For 0.2.5 version users</h3>\n<p>Please run the post_install.py file inside the Scripts folder after downloading from pip.</p>\n<h3 id=\"workarounds\">Workarounds</h3>\n<p>There is a fix to this problem but it requires modifying the code. Modifying the code can lead to more issues.</p>\n<h3 id=\"references\">References</h3>\n<p>There are currently no references to this problem.</p>\n<h3 id=\"note-if-you-get-a-error-regarding-a-function-like---get_key-or-something-like-that-please-re-run-the-file-post_installpy-inside-scripts-folder\">NOTE: If you get a error regarding a function like -&gt; get_key() or something like that, please re-run the file post_install.py inside Scripts folder</h3>\n<h3 id=\"references-1\">References</h3>\n<ul>\n<li><a href=\"https://github.com/AkshuDev/PheonixAppAPI/security/advisories/GHSA-258h-f687-4226\">https://github.com/AkshuDev/PheonixAppAPI/security/advisories/GHSA-258h-f687-4226</a></li>\n<li><a href=\"https://github.com/AkshuDev/PheonixAppAPI/commit/0937419e323f5ea9013d43dc1b82fef9d7e05044\">https://github.com/AkshuDev/PheonixAppAPI/commit/0937419e323f5ea9013d43dc1b82fef9d7e05044</a></li>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2024-41951\">https://nvd.nist.gov/vuln/detail/CVE-2024-41951</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-258h-f687-4226\">https://github.com/advisories/GHSA-258h-f687-4226</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-258h-f687-4226",
            "title": "[PheonixAppAPI] PheonixAppAPI has visible Encoding Maps",
            "date_modified": "2024-11-12T19:39:56.000Z",
            "date_published": "2024-07-31T21:04:28.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-258h-f687-4226"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>Airflow versions before 2.10.3 have a vulnerability that allows authenticated users with audit log access to see sensitive values in audit logs which they should not see.&nbsp;When sensitive variables were set via airflow CLI, values of those variables appeared in the audit log and were stored unencrypted in the Airflow database. While this risk is limited to users with audit log access, it is recommended to upgrade to Airflow 2.10.3 or a later version, which addresses this issue. Users who previously used the CLI to set secret variables should manually delete entries with those variables from the log table.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2024-50378\">https://nvd.nist.gov/vuln/detail/CVE-2024-50378</a></li>\n<li><a href=\"https://github.com/apache/airflow/pull/43123\">https://github.com/apache/airflow/pull/43123</a></li>\n<li><a href=\"https://lists.apache.org/thread/17rxys384lzfd6nhm3fztzgvk47zy7jb\">https://lists.apache.org/thread/17rxys384lzfd6nhm3fztzgvk47zy7jb</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-j857-2pwm-jjmm\">https://github.com/advisories/GHSA-j857-2pwm-jjmm</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-j857-2pwm-jjmm",
            "title": "[apache-airflow] Apache Airflow vulnerable to Insertion of Sensitive Information Into Sent Data",
            "date_modified": "2024-11-08T18:23:52.000Z",
            "date_published": "2024-11-08T15:31:12.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-j857-2pwm-jjmm"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<h3 id=\"summary\">Summary</h3>\n<p>The validation for the file URI scheme falls short, and results in an attacker being able to read any file on the system. This issue only affects instances with a webdriver enabled, and <code>ALLOW_FILE_URI</code> false or not defined.</p>\n<h3 id=\"details\">Details</h3>\n<p>The check used for URL protocol, <code>is_safe_url</code>, allows <code>file:</code> as a URL scheme:</p>\n<p><a href=\"https://github.com/dgtlmoon/changedetection.io/blob/e0abf0b50507a8a3d0c1d8522ab23519b3e4cdf4/changedetectionio/model/Watch.py#L11-L13\">https://github.com/dgtlmoon/changedetection.io/blob/e0abf0b50507a8a3d0c1d8522ab23519b3e4cdf4/changedetectionio/model/Watch.py#L11-L13</a></p>\n<p>It later checks if local files are permitted, but one of the preconditions for the check is that the URL starts with <code>file://</code>. The issue comes with the fact that the file URI scheme is not required to have double slashes.</p>\n<blockquote>\n<p>A valid file URI must therefore begin with either <code>file:/path</code> (no hostname), <code>file:///path</code> (empty hostname), or <code>file://hostname/path</code>.\n— <a href=\"https://en.wikipedia.org/wiki/File_URI_scheme#Number_of_slash_characters\">Wikipedia</a></p>\n</blockquote>\n<p><a href=\"https://github.com/dgtlmoon/changedetection.io/blob/e0abf0b50507a8a3d0c1d8522ab23519b3e4cdf4/changedetectionio/processors/__init__.py#L37-L41\">https://github.com/dgtlmoon/changedetection.io/blob/e0abf0b50507a8a3d0c1d8522ab23519b3e4cdf4/changedetectionio/processors/__init__.py#L37-L41</a></p>\n<h3 id=\"poc\">PoC</h3>\n<ol>\n<li>Open up a changedetection.io instance with a webdriver configured</li>\n<li>Create a new watch: <code>file:/etc/passwd</code> or a similar path for your operating system. Enable webdriver mode</li>\n<li>Wait for it to be checked</li>\n<li>Open preview</li>\n<li>Notice contents of the file</li>\n</ol>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://github.com/dgtlmoon/changedetection.io/security/advisories/GHSA-6jrf-rcjf-245r\">https://github.com/dgtlmoon/changedetection.io/security/advisories/GHSA-6jrf-rcjf-245r</a></li>\n<li><a href=\"https://github.com/dgtlmoon/changedetection.io/commit/49bc982c697169c98b79698889fb9d26f6b3317f\">https://github.com/dgtlmoon/changedetection.io/commit/49bc982c697169c98b79698889fb9d26f6b3317f</a></li>\n<li><a href=\"https://github.com/dgtlmoon/changedetection.io/blob/e0abf0b50507a8a3d0c1d8522ab23519b3e4cdf4/changedetectionio/model/Watch.py#L11-L13\">https://github.com/dgtlmoon/changedetection.io/blob/e0abf0b50507a8a3d0c1d8522ab23519b3e4cdf4/changedetectionio/model/Watch.py#L11-L13</a></li>\n<li><a href=\"https://github.com/dgtlmoon/changedetection.io/blob/e0abf0b50507a8a3d0c1d8522ab23519b3e4cdf4/changedetectionio/processors/__init__.py#L37-L41\">https://github.com/dgtlmoon/changedetection.io/blob/e0abf0b50507a8a3d0c1d8522ab23519b3e4cdf4/changedetectionio/processors/__init__.py#L37-L41</a></li>\n<li><a href=\"https://github.com/dgtlmoon/changedetection.io/releases/tag/0.47.06\">https://github.com/dgtlmoon/changedetection.io/releases/tag/0.47.06</a></li>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2024-51998\">https://nvd.nist.gov/vuln/detail/CVE-2024-51998</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-6jrf-rcjf-245r\">https://github.com/advisories/GHSA-6jrf-rcjf-245r</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-6jrf-rcjf-245r",
            "title": "[changedetection.io] changedetection.io path traversal using file URI scheme without supplying hostname",
            "date_modified": "2024-11-08T13:55:32.000Z",
            "date_published": "2024-11-07T22:00:58.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-6jrf-rcjf-245r"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>In Langchain before 0.0.247, prompt injection allows execution of arbitrary code against the SQL service provided by the chain. </p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2023-32785\">https://nvd.nist.gov/vuln/detail/CVE-2023-32785</a></li>\n<li><a href=\"https://gist.github.com/rharang/9c58d39db8c01db5b7c888e467c0533f\">https://gist.github.com/rharang/9c58d39db8c01db5b7c888e467c0533f</a></li>\n<li><a href=\"https://github.com/langchain-ai/langchain/issues/5923#issuecomment-1696053841\">https://github.com/langchain-ai/langchain/issues/5923#issuecomment-1696053841</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-8h5w-f6q9-wg35\">https://github.com/advisories/GHSA-8h5w-f6q9-wg35</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-8h5w-f6q9-wg35",
            "title": "[langchain] Langchain SQL Injection vulnerability",
            "date_modified": "2024-11-07T15:24:50.000Z",
            "date_published": "2023-10-21T00:30:47.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-8h5w-f6q9-wg35"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>In gradio &lt;=4.42.0, the gr.DownloadButton function has a hidden server-side request forgery (SSRF) vulnerability. The reason is that within the save_url_to_cache function, there are no restrictions on the URL, which allows access to local target resources. This can lead to the download of local resources and sensitive information.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2024-48052\">https://nvd.nist.gov/vuln/detail/CVE-2024-48052</a></li>\n<li><a href=\"https://gist.github.com/AfterSnows/45ffc23797f9127e00755376cc610e12\">https://gist.github.com/AfterSnows/45ffc23797f9127e00755376cc610e12</a></li>\n<li><a href=\"https://rumbling-slice-eb0.notion.site/FULL-SSRF-in-gr-DownloadButton-in-gradio-app-gradio-870b21e0908b48cbafd914719ac1a4e6?pvs=4\">https://rumbling-slice-eb0.notion.site/FULL-SSRF-in-gr-DownloadButton-in-gradio-app-gradio-870b21e0908b48cbafd914719ac1a4e6?pvs=4</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-3gf9-wv65-gwh9\">https://github.com/advisories/GHSA-3gf9-wv65-gwh9</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-3gf9-wv65-gwh9",
            "title": "[gradio] gradio Server Side Request Forgery vulnerability",
            "date_modified": "2024-11-07T15:05:13.000Z",
            "date_published": "2024-11-05T00:31:28.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-3gf9-wv65-gwh9"
            },
            "tags": [
                "severity"
            ]
        }
    ]
}